set -g base-index 1
set -g pane-base-index 1

# Set the terminal title to the tmux session name
set-option -g set-titles on
set-option -g set-titles-string "#{session_name}"

# Keep the pane title in sync (optional but useful)
set-option -g automatic-rename off

# Enable support for Shift+Enter in tmux + iterm2 + ccode
# Ref https://gist.github.com/jftuga/ffa03dbf4cd818f00cc32ce4186d6c1c
bind-key -n S-Enter send-keys Escape "[13;2u"
set -s extended-keys on
set -as terminal-features 'tmux-256color:extkeys'
